<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use App\Entity\Habitude;

#[ORM\Entity]
class Rappel_habitude
{

    #[ORM\Id]
    #[ORM\Column(type: "integer")]
    private int $idRappel;

        #[ORM\ManyToOne(targetEntity: Habitude::class, inversedBy: "rappel_habitudes")]
    #[ORM\JoinColumn(name: 'idHabitude', referencedColumnName: 'id_habitude', onDelete: 'CASCADE')]
    private Habitude $idHabitude;

    #[ORM\Column(type: "string")]
    private string $heureRappel;

    #[ORM\Column(type: "string", length: 50)]
    private string $jours;

    #[ORM\Column(type: "boolean")]
    private bool $actif;

    #[ORM\Column(type: "string", length: 255)]
    private string $message;

    #[ORM\Column(type: "datetime")]
    private \DateTimeInterface $createdAt;

    #[ORM\Column(type: "boolean")]
    private bool $autoGenerated;

    public function getIdRappel()
    {
        return $this->idRappel;
    }

    public function setIdRappel($value)
    {
        $this->idRappel = $value;
    }

    public function getIdHabitude()
    {
        return $this->idHabitude;
    }

    public function setIdHabitude($value)
    {
        $this->idHabitude = $value;
    }

    public function getHeureRappel()
    {
        return $this->heureRappel;
    }

    public function setHeureRappel($value)
    {
        $this->heureRappel = $value;
    }

    public function getJours()
    {
        return $this->jours;
    }

    public function setJours($value)
    {
        $this->jours = $value;
    }

    public function getActif()
    {
        return $this->actif;
    }

    public function setActif($value)
    {
        $this->actif = $value;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage($value)
    {
        $this->message = $value;
    }

    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt($value)
    {
        $this->createdAt = $value;
    }

    public function getAutoGenerated()
    {
        return $this->autoGenerated;
    }

    public function setAutoGenerated($value)
    {
        $this->autoGenerated = $value;
    }
}
