<?php

namespace App\Entity;

use App\Repository\RappelHabitudeRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: RappelHabitudeRepository::class)]
class Rappel_habitude
{
    #[ORM\Id]
    #[ORM\Column(type: 'integer', name: 'id_rappel')]
    private int $idRappel;

    #[ORM\ManyToOne(targetEntity: Habitude::class, inversedBy: 'rappel_habitudes')]
    #[ORM\JoinColumn(name: 'idHabitude', referencedColumnName: 'id_habitude', onDelete: 'CASCADE')]
    #[Assert\NotNull(message: 'Selectionnez une habitude.')]
    private ?Habitude $idHabitude = null;

    #[ORM\Column(type: 'string')]
    #[Assert\NotBlank(message: 'L heure du rappel est obligatoire.')]
    #[Assert\Regex(pattern: '/^\d{2}:\d{2}$/', message: 'Utilisez le format HH:MM.')]
    private string $heureRappel = '08:00';

    #[ORM\Column(type: 'string', length: 50)]
    #[Assert\NotBlank(message: 'Indiquez au moins un jour.')]
    #[Assert\Length(max: 50, maxMessage: 'Le champ jours ne doit pas depasser 50 caracteres.')]
    private string $jours = '';

    #[ORM\Column(type: 'boolean')]
    private bool $actif = true;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank(message: 'Le message du rappel est obligatoire.')]
    #[Assert\Length(max: 255, maxMessage: 'Le message ne doit pas depasser 255 caracteres.')]
    private string $message = '';

    #[ORM\Column(type: 'datetime')]
    #[Assert\NotNull(message: 'La date de creation est obligatoire.')]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: 'boolean')]
    private bool $autoGenerated = false;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $lastSentAt = null;

    public function getIdRappel(): int
    {
        return $this->idRappel;
    }

    public function setIdRappel(int $value): self
    {
        $this->idRappel = $value;

        return $this;
    }

    public function getIdHabitude(): ?Habitude
    {
        return $this->idHabitude;
    }

    public function setIdHabitude(?Habitude $value): self
    {
        $this->idHabitude = $value;

        return $this;
    }

    public function getHeureRappel(): string
    {
        return $this->heureRappel;
    }

    public function setHeureRappel(string $value): self
    {
        $this->heureRappel = $value;

        return $this;
    }

    public function getJours(): string
    {
        return $this->jours;
    }

    public function setJours(string $value): self
    {
        $this->jours = $value;

        return $this;
    }

    public function getActif(): bool
    {
        return $this->actif;
    }

    public function setActif(bool $value): self
    {
        $this->actif = $value;

        return $this;
    }

    public function getMessage(): string
    {
        return $this->message;
    }

    public function setMessage(string $value): self
    {
        $this->message = $value;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $value): self
    {
        $this->createdAt = $value;

        return $this;
    }

    public function getAutoGenerated(): bool
    {
        return $this->autoGenerated;
    }

    public function setAutoGenerated(bool $value): self
    {
        $this->autoGenerated = $value;

        return $this;
    }

    public function getLastSentAt(): ?\DateTimeInterface
    {
        return $this->lastSentAt;
    }

    public function setLastSentAt(?\DateTimeInterface $value): self
    {
        $this->lastSentAt = $value;

        return $this;
    }
}
