# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.journal_screenshot_upload_dir: 'uploads/journals/screenshots'
    app.journal_audio_upload_dir: 'uploads/journals/audio'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\GestionHumeur\JournalAttachmentManager:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $screenshotUploadDir: '%app.journal_screenshot_upload_dir%'
            $audioUploadDir: '%app.journal_audio_upload_dir%'

    Stfalcon\Bundle\TinymceBundle\Twig\Extension\StfalconTinymceExtension:
        arguments:
            $parameterBag: '@parameter_bag'
            $twig: '@twig'
            $packages: '@assets.packages'
            $requestStack: '@request_stack'
        tags: ['twig.extension']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
