<?php

namespace App\Form\Admin\GestionSuiviHabitudes;

use App\Entity\Habitude;
use App\Entity\Rappel_habitude;
use App\Repository\HabitudeRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RappelHabitudeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('idHabitude', EntityType::class, [
                'class' => Habitude::class,
                'choice_label' => 'nom',
                'label' => 'Habitude',
                'placeholder' => 'Choisir une habitude',
                'query_builder' => static fn (HabitudeRepository $repository) => $repository->createQueryBuilder('h')->orderBy('h.nom', 'ASC'),
            ])
            ->add('heureRappel', TextType::class, ['label' => 'Heure (HH:MM)'])
            ->add('jours', TextType::class, [
                'label' => 'Jours',
                'help' => 'Exemple: Lun,Mar,Mer',
            ])
            ->add('actif', CheckboxType::class, [
                'label' => 'Actif',
                'required' => false,
            ])
            ->add('message', TextType::class, ['label' => 'Message'])
            ->add('createdAt', DateTimeType::class, [
                'label' => 'Date de creation',
                'widget' => 'single_text',
            ])
            ->add('autoGenerated', CheckboxType::class, [
                'label' => 'Genere automatiquement',
                'required' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Rappel_habitude::class,
        ]);
    }
}
